apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-web
  labels:
    app: dispatch-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatch-web
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: dispatch-web
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: regsecret
      containers:
        - name: dispatch-web
          image: fiverr/dispatch-web:latest
          imagePullPolicy: IfNotPresent
          command: ["server", "start", "dispatch.main:app", "--host=0.0.0.0"]
          resources:
            requests:
              cpu: 150m
              memory: 1000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 8000
              name: service-port
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8000
            timeoutSeconds: 1
            initialDelaySeconds: 120
            periodSeconds: 3
            failureThreshold: 10
            successThreshold: 1
